### ISSUE TITLE
Sections tracking - Manual vs Automatic

### ISSUE THREAD

**Issue by PrzemyslawKlys** [EvotecIT/OfficeIMO#10]
I try to build everything as it is within the document, loading it when it's requested with the exception of sections. 

I've tried to fix sections: using the code below, but sections are complicated beasts. They move around when adding new sections so I often lost track of sections that just moved because of the new section. Either I don't understand it well enough to build it automatically or the approach I require for Sections to work - is just the way it is. 

```csharp
public List<WordSection> Sections = new List<WordSection>();

private List<WordSection> GetSections() {
    List<WordSection> listSections1 = new List<WordSection>();
    if (_wordprocessingDocument.MainDocumentPart.Document != null) {
        if (_wordprocessingDocument.MainDocumentPart.Document.Body != null) {
            var listElements = _wordprocessingDocument.MainDocumentPart.Document.Body.ChildElements;
            foreach (var element in listElements) {
                if (element is Paragraph) {
                    Paragraph paragraph = (Paragraph)element;
                    if (paragraph.ParagraphProperties != null && paragraph.ParagraphProperties.SectionProperties != null) {
                        listSections1.Add(new WordSection(this, paragraph.ParagraphProperties.SectionProperties, paragraph));
                    }
                }
            }
            var sectionProp = _wordprocessingDocument.MainDocumentPart.Document.Body.ChildElements.OfType<SectionProperties>().FirstOrDefault();
            var section = new WordSection(this, sectionProp, null);
            listSections1.Add(section);
        }
    }
    return listSections1;
}

public List<WordSection> SectionsGenerated {
    get {
        return GetSections();
    }
}
```

Leaving it for the future to either close or fix.

**Comment by eliseudev** [comment]
As I would if I wanted to put a standard font template for every document, without having to use it." SetFontFamily("Segoe UI")" in each paragraph addition?

**Comment by PrzemyslawKlys** [comment]
You sure you got the right issue?

**Comment by eliseudev** [comment]
> Tem certeza que tem o problema certo?

it's not a problem, I just want to know if there's any way to do it.

**Comment by PrzemyslawKlys** [comment]
Don't use existing issue with different problem to ask questions. Open a new issue, that is directly related to your question.
