### ISSUE TITLE
Update fields on open has no effect

### ISSUE THREAD

**Issue by kristofferjalen** [EvotecIT/OfficeIMO#118]
If I add fields to a document:

```
.AddField(WordFieldType.Page)
.AddField(WordFieldType.NumPages)
```

then Word shows a dialog:

> "This document contains fields that may refer to other files. Do you want to update the fields in this document"

Is there any way to avoid this dialog? I have tried using property `UpdateFieldsOnOpen`, but there was no difference:

```
document.Settings.UpdateFieldsOnOpen = true;
```

**Comment by PrzemyslawKlys** [comment]
This is how the fields work, as far as I understand. It's the same with TOC. You can create XML entries, but to get them updated, you force Word to refresh them on open. Isn't what you would expect?

**Comment by kristofferjalen** [comment]
When I insert a page number in Microsoft Word, I don't get that dialog. So the user does not expect such a dialog.

**Comment by PrzemyslawKlys** [comment]
There is a difference between the standard page number which we have available in headers/footers (probably would require some work to get it "anywhere") that is inserted as stdBlock 

```cs
var pageNumber = document.Header.Default.AddPageNumber(WordPageNumberStyle.PlainNumber);
```

![image](https://user-images.githubusercontent.com/15063294/222524169-78dd05a0-f9cd-45e2-a379-da396523e307.png)

And using Fields:

```
document.AddField(WordFieldType.NumPages);
```

![image](https://user-images.githubusercontent.com/15063294/222523901-92dd677e-49d9-4050-88cf-7db5e5cfd760.png)

1st one doesn't force Word to do anything, the other one does (regardless if you have UpdateFields on or don't have nothing added) triggers word to do something. Maybe being inside StdBlocks impacts how it's parsed or maybe the way it's added. Surely there's a difference.
