### ISSUE TITLE
Watermark only a page

### ISSUE THREAD

**Issue by geraluca** [EvotecIT/OfficeIMO#119]
Hello, is it possible to insert the watermark only on a specific page?

**Comment by geraluca** [comment]
I already tried, I created a new section and I added the watermark in the new section, the watermark appears throughout the document

**Comment by PrzemyslawKlys** [comment]
Then it's either not possible (can it be done in Word?) or requires some code changes.

**Comment by geraluca** [comment]
I in Word can not do it but I know that you can do, I also read on the Microsoft site

**Comment by PrzemyslawKlys** [comment]
Unless you provide a sample document showing this and some kind of docs to confirm it's hard to help. If you say "in word you can't do it I doubt you can do it outside of word. Maybe it's just image that is sized as whole page and added in header being behind text and this acts as a watermark.

**Comment by PrzemyslawKlys** [comment]
I was able to add 3 custom watermarks (one one 1st page, one on 2nd page and one that goes on all pages). So it's definitely possible to do it in Word. The question is how to do in code. 

[3 watermarks.docx](https://github.com/EvotecIT/OfficeIMO/files/10875356/3.watermarks.docx)

**Comment by PrzemyslawKlys** [comment]
![image](https://user-images.githubusercontent.com/15063294/222538869-72af713b-febd-4b87-8cc7-81acc0b0692c.png)

So it seems if you put watermark in header it's on all pages but if you put it between Paragraphs it's going to afect only certain pages.

**Comment by PrzemyslawKlys** [comment]
PR was created to address this issue. See PR for details on changes (including breaking changes).
