### ISSUE TITLE
Missing license info

### ISSUE THREAD

**Issue by cezarypiatek** [EvotecIT/OfficeIMO#13]
Hi

Would you mind providing license information for this project/repository?

Thanks!

**Comment by PrzemyslawKlys** [comment]
I am not sure. But feel free to use it commercially. There are no limits basically. I am thinking on MIT, but on the other hand I would like to have ability to have some commercial opportunity in the future. 

If only GitHub sponsorship would work I would gladly make everything MIT like most of my other work on Github.
