### ISSUE TITLE
Allow adding lists to Tables/Paragraphs

### ISSUE THREAD

**Issue by PrzemyslawKlys** [EvotecIT/OfficeIMO#133]
As reported in:
- https://github.com/EvotecIT/PSWriteOffice/issues/14

It should be possible to add lists to Tables, and that means adding them to Paragraphs.

**Comment by tmheath** [comment]
I found the addList method of Paragraph, has this feature been implemented or does this add a list proceeding from a paragraph? I'm asking because if this hasn't been implemented then I need to test for this for what I'm working on and depending on things might do some work here to get a PR going.

**Comment by PrzemyslawKlys** [comment]
Pretty sure it's done:

https://github.com/EvotecIT/OfficeIMO/blob/d8471a948458521d980aed7261abff440d359733/OfficeIMO.Examples/Word/Lists/Lists.Create7.cs#L66-L72

https://github.com/EvotecIT/OfficeIMO/blob/d8471a948458521d980aed7261abff440d359733/OfficeIMO.Examples/Word/Lists/Lists.Create7.cs#L89-L95
