### ISSUE TITLE
Get Footnotes from Document 

### ISSUE THREAD

**Issue by A10s** [EvotecIT/OfficeIMO#152]
How can I find the footnotes of a Word document?

**Comment by PrzemyslawKlys** [comment]
I don't think it's currently supported. Neither are endnotes. 

![image](https://github.com/EvotecIT/OfficeIMO/assets/15063294/db4bec52-540e-4b7f-865a-18f6fea2e3f4)

**Comment by A10s** [comment]
thanks for the quick response

**Comment by PrzemyslawKlys** [comment]
It's probably easier to add some support for it. Not sure if i will have time, but I'll play with it soon

**Comment by PrzemyslawKlys** [comment]
@A10s while I am not done with the PR, maybe this is something that will get you started already. You can add, find foot notes and modify them for now. If you're willing to compile your own version it may be just what you need for now. I'll probably finish it in few days if i get enough time. End notes are not done either.

**Comment by A10s** [comment]
Thanks for the answer. I've already found how to get to the footnotes and the hyperlinks they contain

**Comment by A10s** [comment]
my code:

var doc=WordDocument.Load("test.docx");
var footnotesPart = doc._document.MainDocumentPart?.FootnotesPart;
if (footnotesPart != null)
   {
     var footnotes = footnotesPart.Footnotes.Elements<Footnote>();
     foreach (var f in footnotes)
        {
          var hyperlinks = f.Descendants<Hyperlink>();
               foreach (var hyp in hyperlinks)
                    {
                       var id=hyp.Id;
                       var hrs=footnotesPart .HyperlinkRelationships.Single(q => q.Id == id);
                       var uri= hrs.Uri;
                       ........
                    }
   }}

**Comment by PrzemyslawKlys** [comment]
As long as it works for you ;) My implementation is a bit more complex, but it just simplifies things.

```cs
using (WordDocument document = WordDocument.Load(filePath)) {
    foreach (var footNote in document.FootNotes) {
        foreach (var paragraph1 in footNote.Paragraphs) {
            if (paragraph1.IsHyperLink) {
                paragraph1.Hyperlink.Text = "xxx";
            }
        }
    }
}
```

**Comment by A10s** [comment]
Thank you for your support!
