### ISSUE TITLE
Is any possibility to add Hyperlink inside table cell ? 

### ISSUE THREAD

**Issue by ssasthan** [EvotecIT/OfficeIMO#156]
When using the code below I am encountering the following exception "System.NotImplementedException: There is different parent for paragraphs?".

`table.Rows[rowIndex].Cells[celIndex].Paragraphs[0].AddHyperLink("Google", new Uri("https://www.google.com/"));`

Is there any possible way to add hyperlink inside a table cell ?

**Comment by PrzemyslawKlys** [comment]
Probably my mistake on implementation of Hyperlinks. Needs improvements.

**Comment by PrzemyslawKlys** [comment]
Will be fixed in 0.8.0.
