### ISSUE TITLE
Blank protection password not accepted when trying to unprotect generated word document

### ISSUE THREAD

**Issue by hisuwh** [EvotecIT/OfficeIMO#162]
We are setting protection to `ReadOnly` and setting a blank password so that by default the documents are read-only.  

```csharp
wordDocument.Settings.ProtectionPassword = string.Empty;
wordDocument.Settings.ProtectionType = DocumentProtectionValues.ReadOnly;
```

Our application is intended to act as the single source of truth but we allow users to export documents as PDF or Word documents. 
 However, we don't want to actually block editing the document if the user really wants to.  However, I try and unprotect the document and leave the password blank I get an error from Word:

![image](https://github.com/EvotecIT/OfficeIMO/assets/4470351/bc40ab09-8b9e-4bd4-b47b-e7deaf0e795b)
![image](https://github.com/EvotecIT/OfficeIMO/assets/4470351/15a8f6f6-5cc0-4fc6-9f9a-8b9e440b089a)

Word seems to offer a few more options that might be more what we need but I can't see a way to apply these protections through this library:

![image](https://github.com/EvotecIT/OfficeIMO/assets/4470351/f236af9a-2b69-40c1-bd20-dcf47360965a)
![image](https://github.com/EvotecIT/OfficeIMO/assets/4470351/e9326bdc-2ffb-48fc-bd22-2ed63dc2bba1)

Specifically the latter would be ideal for our purposes:
![image](https://github.com/EvotecIT/OfficeIMO/assets/4470351/56d75744-d7d8-44fd-a662-31387b87acc5)

**Comment by PrzemyslawKlys** [comment]
That's actually looks quite trivial to add if that's all to it.

![image](https://github.com/EvotecIT/OfficeIMO/assets/15063294/603d4073-e36b-4a9c-9221-16576357c180)

Would just require another property under settings, and some basic tests.

```cs
WriteProtection writeProtection1 = new WriteProtection(){ Recommended = true };
return writeProtection1;
```

Tho, when you add that, when you open word you get this prompt which is first time for me.

![image](https://github.com/EvotecIT/OfficeIMO/assets/15063294/5ce72f44-d69f-4ec8-a763-a25b1a537264)

You up for it?

**Comment by PrzemyslawKlys** [comment]
For the Final Mark it seems to be custom property which you already can do manually I guess? 

![image](https://github.com/EvotecIT/OfficeIMO/assets/15063294/1d7aa36e-2e39-4002-bbd1-a472635912c8)

If that would work, we could generate a true/false property in settings as well for that

**Comment by PrzemyslawKlys** [comment]
I've simplified both in the linked PR:
- https://github.com/EvotecIT/OfficeIMO/pull/163
