### ISSUE TITLE
Insert image with fixed position

### ISSUE THREAD

**Issue by boatwrong** [EvotecIT/OfficeIMO#164]
A situation in a project came up where I needed to add an image to a word document with a fixed position. From what I can tell this was not possible to do throught OfficeIMO at the moment. As OpenXML SDK is so complex and offers such thourough control over each element in the document, I wanted to avoid having to compose the element in that way.

What worked for me doing this was to add an additional `WordParagraph.AddImage()` function
```csharp
 public WordParagraph AddImage(Anchor customAnchor, ...) 
```
 that lets the user provide their own `DocumentFormat.OpenXml.Drawing.Wordprocessing.Anchor` object to give finer grain controls over the images position without needing to architect the entire OpenXML structure for where the image is going. This does put the work onto the user for creating there own `Anchor` object however if they look into the codebase at the `GetAnchor()` function used to add images it is quite straightforward to mimic. In my own project is created a personal `GetAnchor()` function that created the positioning I needed for the document.

If this is a feature that is desireable I am ready to open a PR.

**Comment by PrzemyslawKlys** [comment]
I guess the question is - can we expose NewAnchor or something similar that allows user to easily define parameters with simplified logic so they can create it themselves and still maintain it easy to use. Looking at the GetAnchor it's finite number of options there, but maybe i'm oversimplifying it.

I'm happy with you opening a PR, but think on how to simplify it, and if it can't be simplified for reasons it will still be fine. 

But please add at least one example, and some tests around this so that people don't have to guess.

**Comment by boatwrong** [comment]
I think this can be simplified to a single public method for users to add a
fixed position image. 

`GetAnchor()` is a fairly simple method that could have some added parameters and
be exposed as a public method. The only complexity that brings is that you would
also need to pass a `Graphic` object to the `GetAnchor()` method. This feels a
bit circular as you need to create a graphic to create your anchor that you pass
to the `AddImage()` function which creates another image.

From comparing xml from different documents and trial & error, I've gathered that
there are four main components of the `GetAnchor()` method someone would likely
alter:
* the `RelativeFrom` property of the `VerticalPosition` object.
* the `RelativeFrom` property of the `HorizontalPosition` object.
* the `Text` of the `PositionOffset` for the above two objects.
    * the `Text` represents the value in EMU's that someone would enter in the below form.

A "condensed" example of how I implemented this in my project (done in the header of document):

```csharp
using (WordDocument document = WordDocument.Create(report.filePath);

WordHeader header = document.Header.Default;
WordParagraph paragraph = header.AddParagraph();

// First create an image with a file path
WordImage img = new WordImage(document, paragraph, imgFilePath, imgWith, imgHeight, WrapTextImage.Square);

double emuWidth = img.EmuWidth ?? 0.0;
double emuHeight = img.EmuHeight ?? 0.0;
string fileName = img.FileName;
string relationshipId = img.RelationshipId;
ShapeTypeValues shape = img.Shape ?? ShapeTypeValues.Rectangle;
BlipCompressionValues blip = img.CompressionQuality ?? BlipCompressionValues.Print;
string description = img.Description;
Graphic graphic = img.GetGraphic(emuWidth, emuHeight, fileName, relationshipId, shape, blip, description);
string imageName = System.IO.Path.GetFileNameWithoutExtension(fileName);
WrapTextImage wrapText = img.WrapText ?? WrapTextImage.Square;

Anchor newAnchor = customAnchor(emuWidth, emuHeight, graphic, imageName, description, wrapText);

p = p.AddImage(newAnchor, report.iconPath, iconWidth, iconHeight, WrapTextImage.Square);


// Custom method that creates a new anchor. The majority of code was copied from
// GetAnchor of OfficeIMO and the below edits were made.
private static Anchor customAnchor(double emuWidth, double emuHeight, Graphic graphic, string imageName, string description, WrapTextImage wrapImage) {

    ...

    double emusPerInch = 914400.0;
    double offsetInches = 0.4;
    double offsetEmus = offsetInches * emusPerInch;
    VerticalPosition verticalPosition1 = new VerticalPosition() { RelativeFrom = VerticalRelativePositionValues.Page };
    PositionOffset positionOffset2 = new PositionOffset { Text = $"{offsetEmus}" };

    ...
}

```

All that to say, that is a significant amount of complexity for a user when they
only need to edit the horizantal RelativeFrom, horizontal offset, vertical 
RelativeFrom, and vertical offset.

Perhaps a better approach would be to expose a `AddFixedImage()` method that handles
all the complexity but only offers editing the four properties mentioned above?

I'll work on putting that together with examples and tests before opening a PR.

**Comment by PrzemyslawKlys** [comment]
What about exposing properties that change those when the image is already added? In other words, add an image and then change properties that move it around.

**Comment by boatwrong** [comment]
I like that sounds like a lower impact solution - I'll look into this first and test out how changing the properties works.

**Comment by boatwrong** [comment]
Update: Exposing some properties worked perfectly, and is a fairly simple to use abstraction (far simpler than what I hacked together above). Just need to get some examples and tests written up then will be ready to open a PR.

**Comment by boatwrong** [comment]
Feature added by #165

**Comment by boatwrong** [comment]
Feature added in #165
