### ISSUE TITLE
Inserting Tables

### ISSUE THREAD

**Issue by yuphevibing** [EvotecIT/OfficeIMO#172]
Would like to be able to insert a Table at a specific location in the document, not only at the end with the AddTable. Maybe expanding the FindAndReplace method so it would work with tables, or a AddTable method for sections could be solutions.

**Comment by PrzemyslawKlys** [comment]
Pretty sure you can add tables to paragraphs:
- https://github.com/EvotecIT/OfficeIMO/blob/master/OfficeIMO.Examples/Word/Tables/Table.Create7-InsertAfterParagraph.cs
