### ISSUE TITLE
Place Text at specific location

### ISSUE THREAD

**Issue by TopperDEL** [EvotecIT/OfficeIMO#179]
Thank you for this awesome project!

I have a question: can I place Text or a "TextBlock" at a specific location e.g. "2cm from the right border and 3cm from the top border"?
I need to place Adress data and such at exact locations.

**Comment by PrzemyslawKlys** [comment]
Well, how would you do it manually in Word to achieve what you want? 
- Modify margins
- Add a table with hidden borders? 

Both of that you can do. But maybe you are thinking on something else?

**Comment by TopperDEL** [comment]
Is there anything where I can help? Unfortunately I have no clue what needs to be done - but this feature is critical for my app-idea, so I would be very happy to have this included.

Let me know if/how I may help!

**Comment by PrzemyslawKlys** [comment]
This looks similar to how you manage Images. So I will use WordImage type as a starting point and will have to create new type WordTextbox type or something similar. Hopefully it will be enough. 

We will see from there.

**Comment by TopperDEL** [comment]
Awesome!

The project I'm working on should get to the market next year. As soon as I earn something with it I will give back to the projects I'm stacking on top like yours is!

**Comment by PrzemyslawKlys** [comment]
Cool :-) Lets see how that WordTextBox goes first

**Comment by PrzemyslawKlys** [comment]
I got this thing working

```cs
internal static void Example_AddingTextbox2(string folderPath, bool openWord) {
    Console.WriteLine("[*] Creating standard document with some textbox");

    var filePath = System.IO.Path.Combine(folderPath, "BasicDocumentWithTextBox3.docx");

    using (WordDocument document = WordDocument.Create(filePath)) {
        var paragraph = document.AddParagraph("Adding paragraph with some text");

        var textBox = document.AddTextBox("My textbox on the left");

        textBox.HorizontalPositionRelativeFrom = HorizontalRelativePositionValues.Page;
        textBox.HorizonalPositionOffsetCentimeters = 3;
        textBox.HorizontalAlignment = HorizontalAlignmentValues.Left;

        var textBox2 = document.AddTextBox("My textbox on the right");
        textBox2.HorizontalPositionRelativeFrom = HorizontalRelativePositionValues.Page;
        textBox2.HorizonalPositionOffsetCentimeters = 3;
        textBox2.WordParagraph.ParagraphAlignment = JustificationValues.Right;
        textBox2.HorizontalAlignment = HorizontalAlignmentValues.Right;

        document.Save(openWord);
    }
}
```

![image](https://github.com/EvotecIT/OfficeIMO/assets/15063294/7f8560b6-866d-4078-bfb1-6c80a492b7cc)

But need to add some tests and probably there will be things that are going to need improvements. Maybe add some styles that are available in Word. Also the object is very complicated so I am not sure if it will survive testing on real world documents created by other people.

**Comment by TopperDEL** [comment]
Looks awesome! Exactly what I need! Would love to test this out!

**Comment by PrzemyslawKlys** [comment]
There is PR linked to this issue. You can play with it

**Comment by TopperDEL** [comment]
Oh right! Was on my mobile phone and did not realize it. Will try asap!

**Comment by TopperDEL** [comment]
As mentioned in the PR: it works and is exactly what I need! Would love to see it merged. :)
Thank you!

**Comment by PrzemyslawKlys** [comment]
Well that was an easy part. Now the "tests" needs to be done which is less than exciting ;p
