### ISSUE TITLE
TextBox.WidthCentimeters only respected if RelativeWidthPercentage set to 0

### ISSUE THREAD

**Issue by TopperDEL** [EvotecIT/OfficeIMO#183]
See this code:

```
var textBox = document.AddTextBox("My text");
textBox.HeightCentimeters = myHeight;
textBox.WidthCentimeters = myWidth;
```

The height and width are not respected until I set the Percentages to 0:

```
textBox.RelativeWidthPercentage = 0;
textBox.RelativeHeightPercentage = 0;
```

This was not expected. How about clearing the percentage values if the corresponding Centimeters-value is set (and perhaps vice versa)?

**Comment by PrzemyslawKlys** [comment]
Ye, probably should be done. From what I saw in openxml it was clearing it or ignoring (don't remember now), so this should be improved with added tests.
