### ISSUE TITLE
What units are "WordDocument.Margins" in?

### ISSUE THREAD

**Issue by TopperDEL** [EvotecIT/OfficeIMO#184]
I want to set a left margin of 2 centimeters. What value would I have to provide there?

**Comment by TopperDEL** [comment]
Ah, it seems to be Twips (twentieths of a point).

https://www.unitconverters.net/length/millimeter-to-twip.htm

**Comment by PrzemyslawKlys** [comment]
You could always add centimeters properties as it was done in wordtexbox.

**Comment by PrzemyslawKlys** [comment]
Added in:
- https://github.com/EvotecIT/OfficeIMO/pull/200
