### ISSUE TITLE
Questions around TextBox

### ISSUE THREAD

**Issue by TopperDEL** [EvotecIT/OfficeIMO#185]
Sorry to spam you with issues today. :)

I have some questions:
- if I add a TextBox using `document.AddTextBox("My text")` it creates a default paragraph which gets converted to a kind of a "variable" within word. It gets rendered blue by default and I cannot change the text in word. What is is? Can I get a normal text there?
- I tried to create it with `string.Empty` and later use `AddParagraph()' on the TextBox which kind of works, but leaves an empty line before my main paragraph within the TextBox.
- The TextBoxes are not really "above the text". They seem to be paragraphs anchored within the main text. Is there a way to make them fixed on one page and one position?

Thank you for your time and effort on this!

**Comment by PrzemyslawKlys** [comment]
```cs
$varValue = $Document.AddTextbox("Text");
$varValue.WordParagraph.Text =" ChangeText"
$varvalue.WordParagraph.Color = xxx
```

I am not sure I understand, but Textbox has WordParagraph linked to it and it's responsisble how those colors/data looks like.

**Comment by PrzemyslawKlys** [comment]
Maybe defaults couldd be changed.

**Comment by PrzemyslawKlys** [comment]
You need to change Position of it and to what it's relative to? Maybe the defaults are relative to Paragraph?

**Comment by TopperDEL** [comment]
> ```cs
> $varValue = $Document.AddTextbox("Text");
> $varValue.WordParagraph.Text =" ChangeText"
> $varvalue.WordParagraph.Color = xxx
> ```
> 
> I am not sure I understand, but Textbox has WordParagraph linked to it and it's responsisble how those colors/data looks like.

Maybe word recognizes somethin special within? On right click on the blue text it lets me "Remove content control" ("Inhaltssteuerelement entfernen" in german).

**Comment by TopperDEL** [comment]
> You need to change Position of it and to what it's relative to? Maybe the defaults are relative to Paragraph?

So maybe I should add the TextBox on a "Section" or the page itself instead?

**Comment by PrzemyslawKlys** [comment]
It can be on the page, but $varValue has PositionRelativeTo or similar property which you can change.

**Comment by PrzemyslawKlys** [comment]
how would you make it stick when doing it manually?

**Comment by TopperDEL** [comment]
It seems my understanding of Word is wrong. I thought this should do the trick:

![image](https://github.com/EvotecIT/OfficeIMO/assets/1833242/52d083ba-97de-4131-8f34-30812c95145f)

Basically bring the TextBox "In front of the text" so that it is independent of the normal text flow.

**Comment by PrzemyslawKlys** [comment]
ye, so this WordTextBox needs extension for that. I believe it's hardcoded to single value. Unfortunetly I won't have time for a week to take a look at it. 

From what I see when you change it to vor den text it actually adds WrapNone to anchor.

![image](https://github.com/EvotecIT/OfficeIMO/assets/15063294/31c7af7a-285d-4b51-936d-784b80a06457)

In my code it has wraptopbottom

![image](https://github.com/EvotecIT/OfficeIMO/assets/15063294/66d147df-9a22-4d2f-a6e4-733282f7ed62)

So this would need additional get/set logic to look for those "Wrap" types and add them or remove them on demand.

**Comment by TopperDEL** [comment]
I'm still trying to accomplish what I need with word itself. It is not that trivial as it seems. Basically I want to place some text in the first page only and at specific locations. Maybe I first need to add the floating text and afterwards add my fixed textboxes to the first page?
I'm confused.

Don't worry about your timeframe! There is not immediate need to adjust anything. Thank you, though!

**Comment by PrzemyslawKlys** [comment]
Maybe Relative to margin, rather than to page? Dunno, try in Word itself and once you have that ready you can see how the code looks like in Open XML SDK 2.5 Productivity Tool and see what's missing.

**Comment by TopperDEL** [comment]
Ok, I've sorted a bit. Where I was wrong: I have to anchor or add the textboxes within the header/footer. Then they are at a specific location on a page.
I still have the issue with the TextBox-Text being some kind of "variable" within word (rendered as blue text). But I will tackle this later. And come back to here.

**Comment by PrzemyslawKlys** [comment]
It should be fairly easy to add, mostly copy paste. As the textbox attaches between paragraphs so mostly similar to other Add commands. I will be back at work next week. If you figure it out..., if not i'll fix it

**Comment by TopperDEL** [comment]
Just tried a bit but was unsuccessfull. I am confused with the types you have (like WordParagraph) and the types from the OpenXml-library (like Paragraph). I can create a TextBox and a TextBoxContent and add it to your WordDocument - but it does not Show up. I think I need to add my "self created" paragraph to an internal list of your paragraphs?
Will check again tomorrow.

**Comment by PrzemyslawKlys** [comment]
I've made a simple PR showing this functionality. I don't have proper internet/my workstation to work on this, but it does add it to header/footer and you should be able to play with it there.

**Comment by TopperDEL** [comment]
You're awesom! That PR helped alot and I now have a much better understanding of how everything works. I've added some features I needed along the way.

What still confuses me a bit is how you wrap the underlying OpenXML-classes. E.g. if you look at my PR #188 - I've added a feature to add multiple runs and breaks from the text provided. But this is just a quick workaround. You have a similar logic in WordParagraph.PrivateMethos.cs on a WordParagraph. But I cannot use it here because the WordParagraph on a WordTextBox is just a "on-the-fly"-wrapper around the first run of the textbox. Maybe I'm still missing something - but it is not always clear when you have an own class for something and when you use the OpenXML-types.
E.g. my new TextBodyProperties-Property on WordTextBox feels wrong as it gives access to the underlying OpenXML-Type. Should I add dedicated properties for that? But wouldn't that make it just more complex to add every single propertie of every part of all elements?

**Comment by PrzemyslawKlys** [comment]
To be honest I do it on my best guess. I use openxml types if it's pretty clear conversion, but when for example wrap/nowrap/and few other options means you need to add internally few other things I would go create something internal. 

For your specific use case I guess it would make sense to create multiple properties as long as those make sense in exposing them. I usually expose those that I use, but when you use multiple others ... 

Also I believe expanding AddTextbox method with other properties makes sense like position, and other settings that usually means you need to change them anyways. 

I'm experimenting as I go ;)

**Comment by PrzemyslawKlys** [comment]
Keep in mind that NoWrap or Wrap are just one of X number of options available (as per your screenshot). So this can't be a bool, but more likely an enum that causes different code changes.
