### ISSUE TITLE
InvalidProgramException

### ISSUE THREAD

**Issue by Goddfrey** [EvotecIT/OfficeIMO#186]
The line I copied directly from readme, throws an InvalidProgramException "Common Language Runtime detected an invalid program."

```
using (WordDocument document = WordDocument.Create(path)) // this line
{
    // some code
}
```

readme says "The main thing is - it has to work with .NET Framework 4.7.2, .NET Standard 2.0 and so on." so I assumed .NET 8.0 falls under "so on" ;) but I also tried to change my project's target framework to .NET 7.0 which is explicitly mentioned among dependencies, and it still throws the same exception. "Platform target" is "Any CPU" if that matters.

OfficeIMO.Word v 0.12.0 installed via VisualStudio nugget manager

**Comment by PrzemyslawKlys** [comment]
And what happens if you get the whole project and run examples?

**Comment by Goddfrey** [comment]
> And what happens if you get the whole project and run examples?

There were some "file not found in C:/TEMP..." exceptions but when it comes to this particular issue, it seems to work perfectly fine.

**Comment by PrzemyslawKlys** [comment]
Then you're doing something wrong when setting up project. Maybe copy one of examples and try to use them outside?

**Comment by tmpmachine** [comment]
In my case, this one package was causing the issue. Uninstalling it solved the issue.

```csproj
<PackageReference Include="DocumentFormat.OpenXml" Version="3.0.1" />
```

**Comment by PrzemyslawKlys** [comment]
ye, it's newer version than we support:
- https://github.com/EvotecIT/OfficeIMO/issues/192
