### ISSUE TITLE
Open Office Writer can't open document created with OfficeIMO

### ISSUE THREAD

**Issue by Goddfrey** [EvotecIT/OfficeIMO#189]
I'm getting "general input/output error" from Open Office. Here's the code I used to create a test document:

```
int rowCount = 5;
int colCount = 2;

using (WordDocument document = WordDocument.Create(path, true))
{
    var table = document.AddTable(rowCount, colCount, WordTableStyle.GridTable5DarkAccent5);
    for (int i = 0; i < rowCount; i++)
    {
        for (int c = 0; c < colCount; c++)
        {
            string text = "test " + i.ToString();
            table.Rows[i].Cells[c].Paragraphs[0].Text = text;
        }
    }

    document.Save();
}
```
Libre Office opens the same file just fine and I can see the table created. And I don't have MS Word.
[test.docx](https://github.com/EvotecIT/OfficeIMO/files/13887812/test.docx)

Unfortunately OpenOffice can only read .docx it apparently has no way to _save_ a document as .docx so I cannot check what's missing by creating similar table by hand and then extracting and comparing the two.

I did create a similar simple table docx using LibreOffice, that OpenOffice _can_ open, and I can see quite a few differences. Folder **docProps** does not exist in the one created by OfficeIMO. Folder **word** created by Libre Office has 2 subfolders (_rels, theme) and 4 files while the one created by OfficeIMO has same two subfolders and 8 files, and so on. Alas I dont know which of the differences matter and which do not.

**Comment by PrzemyslawKlys** [comment]
Does it work with empty doc? If not can you attach empty for comparison that works?

**Comment by Goddfrey** [comment]
Sure. Although both Open Office and Libre Office are free if you want to run some tests of your own.

[libre_office_empty.docx](https://github.com/EvotecIT/OfficeIMO/files/13914733/libre_office_empty.docx)
[OfficeIMO_empty.docx](https://github.com/EvotecIT/OfficeIMO/files/13914734/OfficeIMO_empty.docx)

I created two empty files docx files, one using Libre Office and another using this code:

```
            using (WordDocument document = WordDocument.Create(path, true))
            {
 
                document.Save();
            }
```

Open Office does open the one created with Libre Office, and does _not_ open the one created with Office IMO.

**Comment by PrzemyslawKlys** [comment]
This needs testing:
- https://www.codeproject.com/Questions/230373/OpenXML-SDK-docx-files-and-Open-Office

Old, but maybe still there.

**Comment by PrzemyslawKlys** [comment]
So i'm pretty confident this is due to forward slash

![image](https://github.com/EvotecIT/OfficeIMO/assets/15063294/77116390-7bad-4c43-9659-bba3fb98f129)
![image](https://github.com/EvotecIT/OfficeIMO/assets/15063294/568dce66-7a41-4e45-a170-7770ccaae5cb)

There are plenty of issues around that:
- https://github.com/dotnet/Open-XML-SDK/issues/249
- https://github.com/dotnet/Open-XML-SDK/issues/59
- https://github.com/dotnet/Open-XML-SDK/issues/88
- https://github.com/dotnet/Open-XML-SDK/issues/86

I saw some project actively changing it:
- https://github.com/sestegra/spreadsheet_decoder/commit/a98df56e54efa4528e7310ab051e33f2c8b865fc

OpenXMLSDK doesn't expose those paths directly from what I see. 

I can see ClosedXML having similar issue:
- https://github.com/ClosedXML/ClosedXML/issues/279

**Comment by PrzemyslawKlys** [comment]
I've created a PR:
- https://github.com/EvotecIT/OfficeIMO/pull/191 

But requires testing, and I am pretty sure this is not the best option to do it like that

**Comment by Rofliex** [comment]
I have the same problem, but new documents created from a template (I use a copy in memory of a document that is on disk) cannot be opened in MS Word, but work correctly in LibreOffice and Google docs :)

**Comment by PrzemyslawKlys** [comment]
You mean created by OfficeIMO? Before or after the PR?

**Comment by Rofliex** [comment]
> You mean created by OfficeIMO? Before or after the PR?

Im didnt test with your changes. Used only latest release from nuget.

**Comment by PrzemyslawKlys** [comment]
Can you test with the PR?

**Comment by Rofliex** [comment]
I found compatibility issues with the property **Paragraph** .**ParagraphAlignment**. If you override this property or set it for a new paragraph, it will cause errors in Ms Word and you will not be able to open a new document.

**Comment by PrzemyslawKlys** [comment]
> I found compatibility issues with the property **Paragraph** .**ParagraphAlignment**. If you override this property or set it for a new paragraph, it will cause errors in Ms Word and you will not be able to open a new document.

So under which conditions exactly your documents don't open? They don't open in MS Word? What is the code you're using - i'm a bit confused what doesn't work for you?

**Comment by Rofliex** [comment]
> > I found compatibility issues with the property **Paragraph** .**ParagraphAlignment**. If you override this property or set it for a new paragraph, it will cause errors in Ms Word and you will not be able to open a new document.
> 
> So under which conditions exactly your documents don't open? They don't open in MS Word? What is the code you're using - i'm a bit confused what doesn't work for you?

I apologize for flooding this issue. In general, if I add any paragraph to a document and define the ParagraphAlignment property using the library, the document stops opening. If I don’t touch the ParagraphAlignment property, then everything opens fine.

**Comment by PrzemyslawKlys** [comment]
So in other words Create Word Document, add paragraph, add paragraph alignment and it stops opening in Word? Which version of word?

**Comment by PrzemyslawKlys** [comment]
```cs
public static void Example_BasicWord(string folderPath, bool openWord) {
    Console.WriteLine("[*] Creating standard document with paragraph");
    string filePath = System.IO.Path.Combine(folderPath, "BasicDocumentWithParagraphs.docx");
    using (WordDocument document = WordDocument.Create(filePath)) {
        var paragraph = document.AddParagraph("Adding paragraph with some text");
        paragraph.ParagraphAlignment = JustificationValues.Center;
        //Console.WriteLine(SixLabors.ImageSharp.Color.Blue.ToHexColor());
        //Console.WriteLine(SixLabors.ImageSharp.Color.Crimson.ToHexColor());
        //Console.WriteLine(SixLabors.ImageSharp.Color.Aquamarine.ToHexColor());

        //paragraph.Color = SixLabors.ImageSharp.Color.Red;

        //paragraph = document.AddParagraph("Adding another paragraph with some more text");
        //paragraph.Bold = true;
        //paragraph = paragraph.AddText(" , but now we also decided to add more text to this paragraph using different style");
        //paragraph.Underline = UnderlineValues.DashLong;
        //paragraph = paragraph.AddText(" , and we still continue adding more text to existing paragraph.");
        //paragraph.Color = SixLabors.ImageSharp.Color.CornflowerBlue;

        document.Save(true);
    }
}
```

I just did this and it worked. You need to be more specific.

**Comment by tmheath** [comment]
I was using LibreOffice for this from home last year, it seemed to work fine.
If it's something specific like how you mentioned the property, I can't say
anything, the documents were simple at the time.

**Comment by tmheath** [comment]
Just noticed this was about OpenOffice... It's a virtually dead project on life support for years, apparently it has a userbase but people really should not be using it, not sure if there's an issue with it being dead or not.
