### ISSUE TITLE
Table styles are not being applied

### ISSUE THREAD

**Issue by SiL3NC3** [EvotecIT/OfficeIMO#19]
Styles are not visible.

> ```cs
>  document.Tables[0].Style = WordTableStyle.GridTable1LightAccent3;
> ```

> ```cs
>  document.AddTable(4, 4, WordTableStyle.GridTable1LightAccent3);
> ```

Both ways are not working or don't seem to have any effect in my document. Possibly a bug?

**Comment by PrzemyslawKlys** [comment]
It could be I only add styles when I create new document, but not on load.
