### ISSUE TITLE
Upgrading DocumentFormat.OpenXML to version 3

### ISSUE THREAD

**Issue by artembrizinskij** [EvotecIT/OfficeIMO#192]
Hello!
Are there any plans to upgrade the DocumentFormat.OpenXML to version 3?

**Comment by PrzemyslawKlys** [comment]
Hi,

I'm kind of waiting for:
- https://github.com/ClosedXML/ClosedXML project to upgrade 

From what I see they do some trick that supports both? I've never seen that before

![image](https://github.com/EvotecIT/OfficeIMO/assets/15063294/63d9001e-0158-4859-b92f-076791e9e8f2)

I am using ClosedXML in my PowerShell projects and the dependency hell is created if the version numbers do not match. 

Not sure if tha setup means they support 3.0.0 and 2.16. 

Also I am not sure what I need to change to get 3.0.0 working. I believe i played with it for a moment and some things will require changes to support it.
