### ISSUE TITLE
Any way to insert rich text HTML content?

### ISSUE THREAD

**Issue by tmpmachine** [EvotecIT/OfficeIMO#203]
I have a requirement to insert rich text content, and currently trying [html agility pack](https://html-agility-pack.net/) by parsing and traversing the DOM.

Just to confirm, OfficeIMO still don't have a feature to insert HTML as word document elements, right? I've checked embedding, but it seems only inserting the plain text of the .html file.

If so, am I on the right path? Is there any other way than traversing manually? maybe any known works or solution that's compatible with OfficeIMO?

**Comment by PrzemyslawKlys** [comment]
```cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using DocumentFormat.OpenXml.Packaging;
using DocumentFormat.OpenXml.Wordprocessing;
using OfficeIMO.Word;

namespace OfficeIMO.Examples.Word {
    internal static partial class Embed {

        public static void Example_EmbedFileHTML(string folderPath, string templateFolder, bool openWord) {
            Console.WriteLine("[*] Creating standard document with embedded HTML file");
            string filePath = System.IO.Path.Combine(folderPath, "EmbeddedFileHTML.docx");
            string htmlFilePath = System.IO.Path.Combine(templateFolder, "SampleFileHTML.html");
            using (WordDocument document = WordDocument.Create(filePath)) {
                Console.WriteLine("Embedded documents in word: " + document.EmbeddedDocuments.Count);
                Console.WriteLine("Embedded documents in Section 0: " + document.Sections[0].EmbeddedDocuments.Count);

                document.AddParagraph("Add HTML document in DOCX");

                document.AddSection();

                Console.WriteLine("Embedded documents in Section 1: " + document.Sections[1].EmbeddedDocuments.Count);

                document.AddEmbeddedDocument(htmlFilePath);

                document.EmbeddedDocuments[0].Save("C:\\TEMP\\EmbeddedFileHTML.html");

                Console.WriteLine("Embedded documents in word: " + document.EmbeddedDocuments.Count);
                Console.WriteLine("Embedded documents in Section 0: " + document.Sections[0].EmbeddedDocuments.Count);
                Console.WriteLine("Embedded documents in Section 1: " + document.Sections[1].EmbeddedDocuments.Count);
                Console.WriteLine("Content type: " + document.EmbeddedDocuments[0].ContentType);

                document.Save(openWord);
            }
        }
    }
}
```

This worked for me when I tried it.

**Comment by tmpmachine** [comment]
Well, yeah, but I was expecting the content to be rendered like the second line here:
![image](https://github.com/EvotecIT/OfficeIMO/assets/18110223/33b1cca4-7dcf-45cc-a968-5d2f9e02ac04)

.. or is it just me? I'm using WPS office, don't have ms word

**Comment by PrzemyslawKlys** [comment]
I tested it on Word and had this working.

When I run:

![image](https://github.com/EvotecIT/OfficeIMO/assets/15063294/5806895a-b6da-4213-a699-eedccbf0e642)

This is the HTML it's embedding:

![image](https://github.com/EvotecIT/OfficeIMO/assets/15063294/f37de0a5-67aa-4533-b9a6-53596f189ed9)

And this is Word:

![image](https://github.com/EvotecIT/OfficeIMO/assets/15063294/192b506a-9301-4c40-b59a-95ef87a2cb9a)

![image](https://github.com/EvotecIT/OfficeIMO/assets/15063294/0126d147-4e4a-4fa5-9071-56686576ef7b)

So it clearly works in Word. Keep in mind that embedding is just putting it in special structure in XML and then the whole "hard work" is done by Word when displaying it. Maybe there's a problem that WPS Office requires some changes to "trigger" that embedding.

**Comment by PrzemyslawKlys** [comment]
For example notice that some things require special fixes for it to open properly 
- https://github.com/EvotecIT/OfficeIMO/pull/191

Maybe you could create some word document in wps office (whatver that is) and compare differences

**Comment by tmpmachine** [comment]
> So it clearly works in Word. Keep in mind that embedding is just putting it in special structure in XML and then the whole "hard work" is done by Word when displaying it. Maybe there's a problem that WPS Office requires some changes to "trigger" that embedding.

That must be it. I asked a friend to open a file and it require installing some plugins or something, and decided not to go with embedding.

There's this library than can convert HTML to openXML: [html2openxml](https://github.com/onizet/html2openxml?tab=readme-ov-file).

The elements collection being parsed by html2openxml is somewhat connected to `DocumentFormat.OpenXml.Wordprocessing.Paragraph`.

![image](https://github.com/EvotecIT/OfficeIMO/assets/18110223/b802cb1f-3103-4796-b092-6b4016789713)

```cs
string filepen = $"C:\\Users\\tmp7\\Desktop\\penman-{Guid.NewGuid().ToString()}.docx";
using (var package = WordprocessingDocument.Create(filepen, WordprocessingDocumentType.Document))
{
    package.AddMainDocumentPart();

    var mainPart = package.MainDocumentPart;
    mainPart.Document = new Document();
    var body = new Body();

    var sectionProp = new SectionProperties();
    var pageSetup = new PageMargin() { Top = 1701, Left = 1134, Right = 1134, Bottom = 850 };
    sectionProp.Append(pageSetup);

    body.Append(sectionProp);

    var converter = new HtmlConverter(mainPart);

    var para = converter.Parse(htmlText);

    var runProp = new RunProperties();
    runProp.Append(new Bold(), new FontSize() { Val = "32" });

    var paragProp = new ParagraphProperties();
    var justif = new Justification() { Val = JustificationValues.Center };
    paragProp.Append(justif);

    foreach (var item in para)
    {
        // <-- item is somewhat connected to DocumentFormat.OpenXml.Wordprocessing.Paragraph
        body.Append(item);
    }
    mainPart.Document.Append(body);
}
```

Then, I found that in [WordParagraph.cs](https://github.com/EvotecIT/OfficeIMO/blob/db169830e223ce975b5e5fb0ccf717fa5653c094/OfficeIMO.Word/WordParagraph.cs#L12), `Paragraph` is `DocumentFormat.OpenXml.Wordprocessing.Paragraph`.
```cs
...
using OfficeMath = DocumentFormat.OpenXml.Math.OfficeMath;
using Paragraph = DocumentFormat.OpenXml.Wordprocessing.Paragraph;
using ParagraphProperties = DocumentFormat.OpenXml.Wordprocessing.ParagraphProperties;
...
```

I still can't quite figure out the solution how to get these converted elements into WordParagraph. Is there a wayto take the XML and directly appending it to the .docx?

**Comment by PrzemyslawKlys** [comment]
I know this library and use it in PSWriteOffice in PowerShell.

We do expose WordProcessingDocument in the document, so you can append things directly to body if you wish. 

![image](https://github.com/EvotecIT/OfficeIMO/assets/15063294/06b6a4e8-905c-4d2a-89ae-3b5b6b947764)

In this case Copilot shows a way, but you can just append whatever you create to it.

**Comment by tmpmachine** [comment]
Awesome! Got it working now, thanks!

![image](https://github.com/EvotecIT/OfficeIMO/assets/18110223/b07b32fc-717b-437a-96c4-bb5343700adf)

```cs
using (WordDocument doc = WordDocument.Create(outputPath))
{
    
    ...
    
    foreach (var item in para)
    {
        doc._document.MainDocumentPart.Document.Body.Append(item);
    }
    
    ...
    
}
```

**Comment by tmpmachine** [comment]
For future reference, if anyone looking for a way to append HTML under a list, you can try to create a table, set the table indent, and put the parsed result into the table.

```cs
using HtmlToOpenXml;

// ....

// # create a single cell table
Table table = new Table();
var tableProperties = new TableProperties(new TableBorders(new TopBorder(), new BottomBorder(), new LeftBorder(), new RightBorder(), new InsideHorizontalBorder(), new InsideVerticalBorder())) { 
    TableIndentation = new TableIndentation() {
        Width = (int)CentimetersToTwips(1.24), // adjust to the list item indent
    }
};
table.AppendChild(tableProperties);

var row = new TableRow();
var cell = new TableCell();
row.Append(cell);
table.Append(row);

// # append table to document body
doc._document.MainDocumentPart.Document.Body.Append(table);


// # parse html
var converter = new HtmlConverter(doc._document.MainDocumentPart);

foreach (OpenXmlCompositeElement item in converter.Parse(htmlText))
{
  // Retrieve the first row and first cell
  TableRow firstRow = table.Elements<TableRow>().FirstOrDefault();
  TableCell firstCell = firstRow?.Elements<TableCell>().FirstOrDefault();

  // # append to table
  firstCell.Append(item);
}
```

**Comment by onizet** [comment]
Hi @tmpmachine , I'm the owner of the mentioned lib. I published a v3 some days ago which bring lots of bug fixes. I'm also supporting now document anchors. I suggest that you give it another try. Thank you

**Comment by PrzemyslawKlys** [comment]
@onizet Thank you. I saw that. I want to update PSWriteOffice with it, but you migrated to 3.0.0 already of OpenXML and Im still waiting for ClosedXML to do the same.
