### ISSUE TITLE
ContentControls.Add() is trimming space from user selection

### ISSUE THREAD

**Issue by achandroth001** [EvotecIT/OfficeIMO#217]
I am trying to select some text and add a content control to this selected text as below.

selection.Range.ContentControls.Add(WdContentControlType.wdContentControlText);

This is trimming out the preceeding space from the selection. Thus converting only the part of the text excluding the trailing space into a control.

How do I achieve this without tampering the existing selected text. With some of the solutions I tried the existing control within the selection is getting removed.

**Comment by PrzemyslawKlys** [comment]
Hi, I'm pretty sure this is not from OfficeIMO as I haven't added anything around ContentControls. Is it part of OpenXML SDK maybe?
