### ISSUE TITLE
How to add image watermark?

### ISSUE THREAD

**Issue by Alex-Yaf** [EvotecIT/OfficeIMO#219]
When adding a watermark, I write this string of code like this:
   "var watermark = document.Sections[0].Header.Default.AddWatermark(WordWatermarkStyle.Image,'imagepath');" But how to add an image? Please advise. Thank you!
![Snipaste_2024-04-12_10-42-59](https://github.com/EvotecIT/OfficeIMO/assets/65864457/a7d0925f-0083-45fc-8208-c43c3f28a4ac)
![Snipaste_2024-04-12_10-46-26](https://github.com/EvotecIT/OfficeIMO/assets/65864457/ec4f116b-9977-43c4-bf05-0e0c6688a09d)

**Comment by PrzemyslawKlys** [comment]
This needs an implementation 🤣I made preparations but didn't finish it.

**Comment by Alex-Yaf** [comment]
> This needs an implementation 🤣I made preparations but didn't finish it.
Okay, if only it could be done quickly. Wishing you all the best in your work!

**Comment by Alex-Yaf** [comment]
oh,tanks!

**Comment by Alex-Yaf** [comment]
oh,thank!
