### ISSUE TITLE
how can I add a table with two rows and each row had diff columns and width?

### ISSUE THREAD

**Issue by coader** [EvotecIT/OfficeIMO#222]
In office, I can merge cells and then split to new columns, then resize the column width of current row.
and how can I do this in OfficeIMO?

**Comment by PrzemyslawKlys** [comment]
You can try to split and/merge Cells:

```cs
wordTable.Rows[0].Cells[1].SplitHorizontally(2);
wordTable.Rows[0].Cells[1].MergeHorizontally(2, true);
```

I am not sure if that will help you with what you're trying to do. Maybe we need to add something that makes this possible.
