### ISSUE TITLE
[Question] Is Save As Web Page support?

### ISSUE THREAD

**Issue by derek-price** [EvotecIT/OfficeIMO#229]
I looked through all the samples but did not see any mention of saving a docx as a "Web Page" like Word provides in the Save menu. 

I did see mention of cloning issues, but that sounded like it was related to saving a new docx.

**Comment by PrzemyslawKlys** [comment]
Save as HTML basically means translating every single paragraph to HTML. Thats a project on its own. While I am toying with this idea there are other projects that try adres this

**Comment by derek-price** [comment]
Okay - thanks for the update!
