### ISSUE TITLE
Repeat as header row at the top on each page

### ISSUE THREAD

**Issue by BorisVolkan** [EvotecIT/OfficeIMO#230]
Hi,

Does WordTable supports **Repeat as header row at the top on each page** feature?

**Comment by PrzemyslawKlys** [comment]
No, but it seems to be pretty easy to add:

![image](https://github.com/EvotecIT/OfficeIMO/assets/15063294/a6751b30-4fe3-4b8b-8742-9f0f3e53ff31)


Basically one needs to add TableHeaderr() to TableRowProperties, for every row to enable it, and remove it to disable.

**Comment by BorisVolkan** [comment]
But how do I know when page break occurs to enable it?

**Comment by PrzemyslawKlys** [comment]
I mean you can just enable it on all tables? The Word will take care of it. If there's page break, it will use it, if there isn't - nothing will happen. In Word there's no way to tell on which page you are unless you basically implement what Word does as far as I am aware.

**Comment by BorisVolkan** [comment]
Thank you

**Comment by BorisVolkan** [comment]
RepeatHeaderRowAtTheTopOfEachPage should be applied on FirstRow. (the header) not on a table level. Now it creates page break before table.

**Comment by BorisVolkan** [comment]
Now it is OK. Thank you.
