### ISSUE TITLE
How do I set the first column style of a table not to be bold

### ISSUE THREAD

**Issue by taoranxy** [EvotecIT/OfficeIMO#235]
WordTable is set unbolded. I want WordTableStyle to be selected so that the first column of the non-first row is unbolded, but only one of the WordTableStyle enumerations can do that.
i set the value according to the example (wordTable.Rows[i].Cells[j].Paragraphs[0].Bold = false), 
![image](https://github.com/user-attachments/assets/e268a287-c61c-4f8e-aa64-e10687759842)
![image](https://github.com/user-attachments/assets/2f24482e-9f26-4e7c-b434-f53c3640edf6)

but it does not take effect when exported, and the text in the first column of the non-first row is still Bold, whereas if I set bold for all Paragraphs in all Cells = true, all the text in the cell is bolded when exporting, can you tell me how to set it?
![image](https://github.com/user-attachments/assets/7fb1a8fc-a0e8-47fd-8248-95825d71dbae)
![Uploading image.png…]()

**Comment by PrzemyslawKlys** [comment]
I think it's related to Conditional Formatting:
- Check https://github.com/EvotecIT/OfficeIMO/issues/227

```cs
wordTable.ConditionalFormattingFirstRow = true;
wordTable.ConditionalFormattingLastRow = true;
wordTable.ConditionalFormattingFirstColumn = false;
```

Does it work?

**Comment by taoranxy** [comment]
Thank you so much for your help. I did it
