### ISSUE TITLE
Superscript / subscript support?

### ISSUE THREAD

**Issue by ChrisBellBO** [EvotecIT/OfficeIMO#242]
I may be missing something but it doesn't seem like there is a way to find out if a paragraph has superscript or subscript applied? It looks like the run properties has a VerticalTextAlignment property that has a value of superscript

**Comment by PrzemyslawKlys** [comment]
Ye, this functionality seems to be missing and needs to be added/exposed:

![image](https://github.com/user-attachments/assets/f6507250-f84a-459f-9290-0511479ad0c1)

**Comment by PrzemyslawKlys** [comment]
Solved by: https://github.com/EvotecIT/OfficeIMO/pull/240
