### ISSUE TITLE
AddTab should be Public not internal

### ISSUE THREAD

**Issue by londonwallops** [EvotecIT/OfficeIMO#259]
In the file WordTabStop.cs, the method:

internal WordTabStop AddTab(int position, TabStopValues? alignment = null, TabStopLeaderCharValues? leader = null)

should be public, as currently it cannot be used outside of the OfficeIMO namespace. This is on line 57 if that helps.

**Comment by londonwallops** [comment]
Also in this file ideally we would have a public method that would expose the _paragraph field. An example of what could be added is below:

public WordParagraph Paragraph {
    get { return _paragraph; }
}

**Comment by londonwallops** [comment]
I was trying to edit the indentation of a paragraph in word using the following code 

var section1 = masterList.AddItem("text in the paragraph", 0).SetBold(true);

// Convert 1.5 cm to twips (851 twips)
int tabStopPositionInTwips = Convert.ToInt32(1.5 * 28.35 * 20);

// Create a WordTabStop object and add the tab stop
var tabStopHandler = new WordTabStop(section1);
tabStopHandler.AddTab(tabStopPositionInTwips, TabStopValues.Left, TabStopLeaderCharValues.None);

But it cant access it. I have managed to find a workaround for this issue though, by using an extension class and accessing it through that. It isn't crucial that this is changed but it would make my code significantly cleaner!

**Comment by PrzemyslawKlys** [comment]
And why you can't use it this way?

```cs
Console.WriteLine("[*] Creating standard document with paragraphs");
string filePath = System.IO.Path.Combine(folderPath, "Basic Document with some tab stops.docx");
using (WordDocument document = WordDocument.Create(filePath)) {
    var paragraph = document.AddParagraph("\tFirst Line");

    document.Settings.DefaultTabStop = 2880;
    document.Settings.CharacterSpacingControl = CharacterSpacingValues.DoNotCompress;

    Console.WriteLine("Tabs count: " + paragraph.TabStops.Count);

    var tab1 = paragraph.AddTabStop(1440);

    var tab2 = paragraph.AddTabStop(1440);
    tab2.Alignment = TabStopValues.Left;
    tab2.Leader = TabStopLeaderCharValues.Hyphen;
    tab2.Position = 1440;

    paragraph.AddText("\tMore text");

    Console.WriteLine($"Tabs count: " + paragraph.TabStops.Count);

    var paragraph1 = document.AddParagraph("\tNext Line");

    var tab3 = paragraph1.AddTabStop(5000);
    tab3.Leader = TabStopLeaderCharValues.Hyphen;

    var tab4 = paragraph1.AddTabStop(1440 * 2);
    paragraph1.AddText("\tEven more text");

    Console.WriteLine("Tabs for Paragraph2 count: " + paragraph.TabStops.Count);
    Console.WriteLine("Tabs for Paragraph1 count: " + paragraph1.TabStops.Count);
    Console.WriteLine("Default tab stop: " + document.Settings.DefaultTabStop);
    Console.WriteLine("Default tab stop: " + document.Settings.CharacterSpacingControl);

    document.Save();
}
```

**Comment by PrzemyslawKlys** [comment]
Solved?

**Comment by londonwallops** [comment]
I have found a workaround for this yes, I have added an extension class to access it as if it were public.

**Comment by PrzemyslawKlys** [comment]
That was not the question...

**Comment by londonwallops** [comment]
I haven't tried the code you suggested because I have already found a solution. In answer to your question, yes, it is solved. Thanks for the help nonetheless!
