### ISSUE TITLE
Option to save to Stream rather than file path

### ISSUE THREAD

**Issue by hisuwh** [EvotecIT/OfficeIMO#38]
I am developing a web application and want to be able to generate a word document to then be downloaded by the user.

This library does not give me the option to save to a Stream only a file path

**Comment by hisuwh** [comment]
Actually I've realised the underlying document object is public so I can do this

```c#
var resultStream = new MemoryStream();
document._wordprocessingDocument.Clone(resultStream);
resultStream.Seek(0, SeekOrigin.Begin);
```

Might be nice to have a first class method though?

**Comment by hisuwh** [comment]
Here you go: https://github.com/EvotecIT/OfficeIMO/pull/43

**Comment by PrzemyslawKlys** [comment]
@hisuwh Tests are failing tho?
