### ISSUE TITLE
Opinion: Focus on word and ignore Excel

### ISSUE THREAD

**Issue by hisuwh** [EvotecIT/OfficeIMO#40]
I notice in your code there is the start of an implementation for Excel.  If you are not already aware there is excellent library for Excel already: https://spreadsheetlight.com/

However, I have not seen another open-source Word library.  I think efforts would be best focussed on that.  This looks really good already, but would great to have this fully fleshed out alongside SpreadsheetLight as complete solution for Word and Excel.

Just my opinion of course, feel free to do what you think is best.

**Comment by PrzemyslawKlys** [comment]
Excel is just a playground for me. We may need some code to embed excel in Word - I've no plans to build on top of it unless I am forced to. I use https://github.com/ClosedXML/ClosedXML, I used to use EPPlus, but they changed their license, making it harder to use.
