### ISSUE TITLE
SetFontFamily pattern for every document created

### ISSUE THREAD

**Issue by eliseudev** [EvotecIT/OfficeIMO#45]
Would you have to set a default FontFamily for every document, without having to add to each paragraph you create?

follows the example in the image.

![image](https://user-images.githubusercontent.com/80722576/195902559-875e2ee5-6751-4dee-82ec-33b27435ef05.png)

**Comment by PrzemyslawKlys** [comment]
It's not exposed now, but I would suggest doing this differently. Just work without setting font family and then once everything is done just loop thru all paragraphs 

```csharp
foreach (var paragraph in document.Paragraphs) {
    paragraph.SetFontFamily(...).SetFontSize(10)
}
```

You will fix this in 3 lines. I'll keep this open, as it should be possible to define default font.

**Comment by eliseudev** [comment]
> Não está exposto agora, mas eu sugeriria fazer isso de forma diferente. Basta trabalhar sem definir a família font e, em seguida, uma vez que tudo é feito apenas loop th através de todos os parágrafos
> 
> ```cs
> foreach (var paragraph in document.Paragraphs) {
>     paragraph.SetFontFamily(...).SetFontSize(10)
> }
> ```
> 
> Você vai consertar isso em 3 linhas. Vou manter isso aberto, pois deve ser possível definir fonte padrão/style.

Thanks, I thought I had a generic method, but so too solves my problem.

**Comment by PrzemyslawKlys** [comment]
I will add native way to do it in next release:
- https://github.com/EvotecIT/OfficeIMO/pull/48

**Comment by PrzemyslawKlys** [comment]
PR was merged

```csharp
      public static void Example_BasicWordWithDefaultStyleChange(string folderPath, bool openWord) {
            Console.WriteLine("[*] Creating standard document with different default style");
            string filePath = System.IO.Path.Combine(folderPath, "BasicWordWithDefaultStyleChange.docx");
            using (WordDocument document = WordDocument.Create(filePath)) {
                document.Settings.FontSize = 30;
                document.Settings.FontFamily = "Calibri Light";
                document.Settings.Language = "pl-PL";

                var paragraph1 = document.AddParagraph("To jest po polsku");

                var paragraph2 = document.AddParagraph("Adding paragraph1 with some text and pressing ENTER");
                paragraph2.FontSize = 15;
                paragraph2.FontFamily = "Courier New";

                document.Save(openWord);
            }
        }
```

Should be available in next version

**Comment by eliseudev** [comment]
Sorry, but in Settings there is no FontSize.

![image](https://user-images.githubusercontent.com/80722576/196430120-ce3d2750-c581-4f8a-b0a1-65338e4637cc.png)
