### ISSUE TITLE
 Set special characters to the document's default font.

### ISSUE THREAD

**Issue by eliseudev** [EvotecIT/OfficeIMO#54]
Hello, I wanted to know if there's a way to set the default font for special characters for example, I put the default font in the "Segoe UI" document, but when it has a special character it stays with the "Calibri" font, how can I adjust it? Note, the font supports special characters. (follow the prints)

![image](https://user-images.githubusercontent.com/80722576/198022733-8cec19ad-0ed9-4e24-901c-80ff138e9bb0.png)
<br>
<br>
<br>
![image](https://user-images.githubusercontent.com/80722576/198022751-b4faf026-b1fe-4211-950c-342ddbee03a5.png)

**Comment by PrzemyslawKlys** [comment]
Can you provide some "code" that will generate this, so I can do testing and provide options?

**Comment by eliseudev** [comment]
> Você pode fornecer algum "código" que irá gerar isso, para que eu possa fazer testes e fornecer opções?

**Comment by eliseudev** [comment]
> Can you provide some "code" that will generate this, so I can do testing and provide options?

` using (WordDocument document = WordDocument.Create(filePath))
                {
                    document.Settings.Language = "pt-Br";

                    string title = "INSTRUMENTO PARTICULAR DE CONSTITUIÇÃO DE GARANTIA DE\r\nALIENAÇÃO FIDUCIÁRIA DE IMÓVEL\r\n";

 document.AddParagraph(title).SetBold().ParagraphAlignment = JustificationValues.Center;
document.Save();
`

that's just the title, I need to adjust it in every document.
