### ISSUE TITLE
Set special characters to the document's default font.

### ISSUE THREAD

**Issue by eliseudev** [EvotecIT/OfficeIMO#55]
Hello, I wanted to know if there's a way to set the default font for special characters for example, I put the default font in the "Segoe UI" document, but when it has a special character it stays with the "Calibri" font, how can I adjust it? Note, the font supports special characters. (follow the prints)

![image](https://user-images.githubusercontent.com/80722576/198309630-55191fc3-1865-4f7f-97a4-d6d8fa2bea29.png)
<br>
<br>
![image](https://user-images.githubusercontent.com/80722576/198309766-170273bd-5639-4397-9d6d-cef5c757f09a.png)

```
using (WordDocument document = WordDocument.Create(filePath))
                {
                    document.Settings.Language = "pt-Br";

                    string title = "INSTRUMENTO PARTICULAR DE CONSTITUIÇÃO DE GARANTIA DE\r\nALIENAÇÃO FIDUCIÁRIA DE IMÓVEL\r\n";

 document.AddParagraph(title).SetBold().ParagraphAlignment = JustificationValues.Center;
document.Save();
```

that's just the title, I need to adjust it in every document.

**Comment by PrzemyslawKlys** [comment]
I don't understand - why second issue?
- https://github.com/EvotecIT/OfficeIMO/issues/54

**Comment by eliseudev** [comment]
> Não entendo por que segunda questão?
> 
> * [ Set special characters to the document's default font. #54](https://github.com/EvotecIT/OfficeIMO/issues/54)

Why didn't you answer the other one, can you help me?

**Comment by PrzemyslawKlys** [comment]
This is a free project. As such, I fix things when I have time, I answer when I have time. Nobody pays me to do it. I do it in my own free time.

**Comment by eliseudev** [comment]
> Este é um projeto gratuito. Como tal, eu conserto as coisas quando tenho tempo, eu respondo quando tenho tempo. Ninguém me paga para fazer isso. Faço isso no meu próprio tempo livre.

Yes, I know, I'm sorry it's because I'm using it in a big project and it has no documentation, and I'm having this problem when it generates the word file.

**Comment by eliseudev** [comment]
> Este é um projeto gratuito. Como tal, eu conserto as coisas quando tenho tempo, eu respondo quando tenho tempo. Ninguém me paga para fazer isso. Faço isso no meu próprio tempo livre.

If you could help me, I'd be grateful.

**Comment by PrzemyslawKlys** [comment]
I will take a look at it tomorrow or during the weekend.

**Comment by eliseudev** [comment]
I noticed that the generated document it opens in "compatibility mode", in which office version is it generated? is there a way I can set the version?

**Comment by PrzemyslawKlys** [comment]
It's not implemnented. Please open separate issue so it can be added, do not highjack other issues. It will require some investigation
