### ISSUE TITLE
compatibility mode

### ISSUE THREAD

**Issue by eliseudev** [EvotecIT/OfficeIMO#57]
I noticed that the generated document it opens in "compatibility mode", in which office version is it generated? is there a way I can set the version? and which version it is saved?

**Comment by PrzemyslawKlys** [comment]
Looking at code created by Word this needs to be investigated if it solves an issue. 

```csharp
            Compatibility compatibility1 = new Compatibility();
            CompatibilitySetting compatibilitySetting1 = new CompatibilitySetting(){ Name = CompatSettingNameValues.CompatibilityMode, Uri = "http://schemas.microsoft.com/office/word", Val = "15" };
            CompatibilitySetting compatibilitySetting2 = new CompatibilitySetting(){ Name = CompatSettingNameValues.OverrideTableStyleFontSizeAndJustification, Uri = "http://schemas.microsoft.com/office/word", Val = "1" };
            CompatibilitySetting compatibilitySetting3 = new CompatibilitySetting(){ Name = CompatSettingNameValues.EnableOpenTypeFeatures, Uri = "http://schemas.microsoft.com/office/word", Val = "1" };
            CompatibilitySetting compatibilitySetting4 = new CompatibilitySetting(){ Name = CompatSettingNameValues.DoNotFlipMirrorIndents, Uri = "http://schemas.microsoft.com/office/word", Val = "1" };
            CompatibilitySetting compatibilitySetting5 = new CompatibilitySetting(){ Name = CompatSettingNameValues.DifferentiateMultirowTableHeaders, Uri = "http://schemas.microsoft.com/office/word", Val = "1" };
            CompatibilitySetting compatibilitySetting6 = new CompatibilitySetting(){ Name = new EnumValue<CompatSettingNameValues>() { InnerText = "useWord2013TrackBottomHyphenation"}, Uri = "http://schemas.microsoft.com/office/word", Val = "0" };

            compatibility1.Append(compatibilitySetting1);
            compatibility1.Append(compatibilitySetting2);
            compatibility1.Append(compatibilitySetting3);
            compatibility1.Append(compatibilitySetting4);
            compatibility1.Append(compatibilitySetting5);
            compatibility1.Append(compatibilitySetting6);
```

**Comment by eliseudev** [comment]
> Looking at code created by Word this needs to be investigated if it solves an issue.
> 
> ```cs
>             Compatibility compatibility1 = new Compatibility();
>             CompatibilitySetting compatibilitySetting1 = new CompatibilitySetting(){ Name = CompatSettingNameValues.CompatibilityMode, Uri = "http://schemas.microsoft.com/office/word", Val = "15" };
>             CompatibilitySetting compatibilitySetting2 = new CompatibilitySetting(){ Name = CompatSettingNameValues.OverrideTableStyleFontSizeAndJustification, Uri = "http://schemas.microsoft.com/office/word", Val = "1" };
>             CompatibilitySetting compatibilitySetting3 = new CompatibilitySetting(){ Name = CompatSettingNameValues.EnableOpenTypeFeatures, Uri = "http://schemas.microsoft.com/office/word", Val = "1" };
>             CompatibilitySetting compatibilitySetting4 = new CompatibilitySetting(){ Name = CompatSettingNameValues.DoNotFlipMirrorIndents, Uri = "http://schemas.microsoft.com/office/word", Val = "1" };
>             CompatibilitySetting compatibilitySetting5 = new CompatibilitySetting(){ Name = CompatSettingNameValues.DifferentiateMultirowTableHeaders, Uri = "http://schemas.microsoft.com/office/word", Val = "1" };
>             CompatibilitySetting compatibilitySetting6 = new CompatibilitySetting(){ Name = new EnumValue<CompatSettingNameValues>() { InnerText = "useWord2013TrackBottomHyphenation"}, Uri = "http://schemas.microsoft.com/office/word", Val = "0" };
> 
>             compatibility1.Append(compatibilitySetting1);
>             compatibility1.Append(compatibilitySetting2);
>             compatibility1.Append(compatibilitySetting3);
>             compatibility1.Append(compatibilitySetting4);
>             compatibility1.Append(compatibilitySetting5);
>             compatibility1.Append(compatibilitySetting6);
> ```

I'm sorry, but it didn't work out.

**Comment by PrzemyslawKlys** [comment]
Maybe i wasn't clear. This requires to be integrated internally as it needs to be assigned to word/settings. So you would need to append it into the source code, and not just paste it in your code.

![image](https://user-images.githubusercontent.com/15063294/198586799-db2db920-b915-4c43-a410-29d074c6d61e.png)

**Comment by eliseudev** [comment]
> Talvez eu não tenha sido claro. Isso requer ser integrado internamente, pois precisa ser atribuído a palavras/configurações. Então você precisaria apê-lo no código fonte, e não apenas colá-lo em seu código.
> 
> ![image](https://user-images.githubusercontent.com/15063294/198586799-db2db920-b915-4c43-a410-29d074c6d61e.png)

in your library??? I still don't get it.

**Comment by PrzemyslawKlys** [comment]
I have to fix it inside my NUGET. Unless you're willing to do edits yourself and prepare a PR, there's nothing you can do for now.

**Comment by eliseudev** [comment]
> Tenho que consertar isso dentro do meu NUGET. A menos que esteja disposto a editar-se e preparar um RP, não há nada que você possa fazer por enquanto.

I will see if I can talk to the project manager and wait for you to update, thanks for the feedback.
