### ISSUE TITLE
Extending field type list

### ISSUE THREAD

**Issue by byteSamurai** [EvotecIT/OfficeIMO#71]
Hey, 
At the moment, I have struggles to add custom field codes because the enum does not contain the [whole list of field codes](https://support.microsoft.com/en-us/office/list-of-field-codes-in-word-1ad6d91a-55a7-4a8d-b535-cf7888659a51), but only a subset:
https://github.com/EvotecIT/OfficeIMO/blob/master/OfficeIMO.Word/WordField.cs#L10

E.g., could we add `BIBLIOGRAPHY` to it? 
See: https://support.microsoft.com/en-us/office/field-codes-bibliography-field-cbb17838-05d7-4533-8066-4791aeddb9de

Some field codes require switches, so how about passing a dictionary to `AddField(...)` as an optional argument?

Do you think that is doable? Do you prefer a PR or to do it yourself?

**Comment by PrzemyslawKlys** [comment]
Hi, 

I've implemented what I actually tested works and that I mostly understood. I am not sure how all other fields behave and whether or not those can be easily defined the same way. If you know how all those are handled I would be more than happy to get a PR. I would love people to join in - as I have no clue what I am doping most of the time. 

Please make sure to add couple of examples/tests. 

Przemek

**Comment by PrzemyslawKlys** [comment]
> > as I have no clue what I am doping most of the time
> 
> Yeah yeah... the humble MS MVPs 😏

My MVP title is for Cloud & Datacenter, aka Sysadmin/PowerShell stuff. Playing with C# is my hobby, and I just tend to use my skill of bashing my head against the wall long enough for patterns to emerge and I somehow get it to work. Then copilot, resharper and VS enterprise comes in with some advice and things seems to work out better or worse. But I am far from knowing what I am actually doing with openxml🤣😂

**Comment by PrzemyslawKlys** [comment]
No, go ahead. The very first version I created had a lot of stuff that was calculated by me and I was doing all the tracking what changes and how. Once I had a working model with tests I decided to go back and rewrite all the properties/methods to get stuff dynamically with the exception of sections. There are a lot of left-overs like this in code. Some are commented out, some are not. I just wasn't sure if the new code is stable enough. Maybe it should be done as part of separate PR (as in Cleanup having it's own, and this topic having it's own, unless it directly influences what you're doing with this topic then it can be in one PR - at least I think

**Comment by PrzemyslawKlys** [comment]
Hi,

- I have Windows 11 with Visual Studio 2022 Enterprise 
- .NET Standard 2.0 and .NET Standard 2.1 is supported, and quite a lot of frameworks are supported

![image](https://user-images.githubusercontent.com/15063294/202528750-f9b32430-c91d-4533-81b0-adefb3c965f3.png)

It's actually very useful for PowerShell where with one LIB you are able to support both PS 5.1 and PS 7 which is the main reason I created this project. 

As you can see in the project there are 3 systems tested on Azure Devops - linux, windows, macos. As long as we retain tests for all supported frameworks on all supported systems we can adjust the settings to be runnable on all systems as required. Maybe it just needs some IF/ELSE in the configuration settings depending on OS version.
