### ISSUE TITLE
When I am upgrading from 0.4.0 to 0.4.1 Lists do not show up anymore

### ISSUE THREAD

**Issue by surematu** [EvotecIT/OfficeIMO#82]
Hello.
I'm sorry but I do not really know how to publish a issue in github, so please ask if any more information is needed.

**What I do:**
Run the code example for an advance document from the readme, also tried the exmaple where
Tried with .net 4.7.2, .net 5, .net 6 and .net 7. They all return the same issue.

Also tried the list code that was updated 18 days ago, where it describe some of the same issue, lists not appearing.
#62 Fix not saving list when save to Stream
[OfficeIMO/OfficeIMO.Examples/Word/Lists/Lists.Create2.cs](https://github.com/EvotecIT/OfficeIMO/blob/master/OfficeIMO.Examples/Word/Lists/Lists.Create2.cs)

**Issue:**
On version 0.4.0 tittles, lists and TOC appears like normal. When I run the code example after upgrading to 0.4, text from the list appears, but not the bulletpoint itself. The titles lacks formating. See picture bellow.

**Picture:**
![image](https://user-images.githubusercontent.com/1349705/203741568-2d6a28a5-c6b0-403a-b6ef-ed48677eaa06.png)

**Comment by PrzemyslawKlys** [comment]
It does seem broken. Could be related to change 
- https://github.com/EvotecIT/OfficeIMO/pull/76 by @rstm-sf 
- https://github.com/EvotecIT/OfficeIMO/pull/62

**Comment by PrzemyslawKlys** [comment]
I can confirm this is related to change in #76. Rewerting whole class brings back numbering

![image](https://user-images.githubusercontent.com/15063294/204033596-496cfa5e-a413-4a6f-9c63-63f40b3dde48.png)

**Comment by PrzemyslawKlys** [comment]
Ok, so the issue is the order of run and paragraph properties does matter. 

Proper order is:
- paragraph contains paragraph properties and then it can have a run. 

In the @rstm-sf PR the order is:

![image](https://user-images.githubusercontent.com/15063294/204035209-74d941a7-eeb8-463e-83d3-ca0088a36523.png)

When it should be:

![image](https://user-images.githubusercontent.com/15063294/204034920-20d9b488-4139-44c6-aca4-1e818ed16caf.png)

**Comment by PrzemyslawKlys** [comment]
The PR fixes the issue, but we need to add more tests for cases like this,, to check order of paragraphs objects.
