### ISSUE TITLE
Reading distributed/interrupted instructions of field codes causes an exception

### ISSUE THREAD

**Issue by byteSamurai** [EvotecIT/OfficeIMO#94]
I just stumbled upon an issue. Given this markup from a off-the-shelf Word document:
```xml
<w:r w:rsidR="006B53C8">
    <w:fldChar w:fldCharType="begin" />
</w:r>
<w:r w:rsidR="006B53C8">
    <w:instrText xml:space="preserve"> XE "</w:instrText>
</w:r>
<w:r w:rsidR="006B53C8" w:rsidRPr="00D01158">
    <w:instrText>Introduction</w:instrText>
</w:r>
<w:r w:rsidR="006B53C8">
    <w:instrText xml:space="preserve">" </w:instrText>
</w:r>
<w:r w:rsidR="006B53C8">
    <w:fldChar w:fldCharType="end" />
</w:r>
```
 From the document:
 
<img src="https://user-images.githubusercontent.com/6654064/211378827-727a31e8-c807-4f92-bd4f-4b8f87f2f1b1.png" width=400 />

### Expected Behaviour

The instruction text will be concatenated to form the string `XE "Introduction"`

### Actual Behaviour
An Exception will be thrown, because the detected fieldCode is just `XE "`:
```
Unhandled exception. System.NotImplementedException: The missing part """ of the field code "XE "" couldn't be processed by the Parser
   at OfficeIMO.Word.WordFieldParser.ParseFieldCodeDeclaration(String fieldCodeDeclaration) in /home/f/OfficeIMO/OfficeIMO.Word/WordFieldParser.cs:line 118
   at OfficeIMO.Word.WordFieldParser..ctor(String fieldCodeDeclaration) in /home/f/OfficeIMO/OfficeIMO.Word/WordFieldParser.cs:line 56
   at OfficeIMO.Word.WordField.get_FieldType() in /home/f/OfficeIMO/OfficeIMO.Word/WordField.cs:line 107
   ```
   
 ### Possible Fix Suggestions
- Improve the reading/parsing of the document regarding field codes
- Replace [the exception](https://github.com/EvotecIT/OfficeIMO/blob/master/OfficeIMO.Word/WordFieldParser.cs#L118) with an Console Warning and work with incorrectly read/parsed document

**Comment by PrzemyslawKlys** [comment]
Option 1, of course.

**Comment by PrzemyslawKlys** [comment]
Tests would be good for this case. Leaving it open unless you think it's not needed.
